# Further reading https://medium.com/@swayamraina/why-every-team-should-use-git-hooks-9c1c393a8a53
gemfile: Gemfile

PreCommit:
  Mdl:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true

  # https://github.com/tcort/markdown-link-check#config-file-format
  MarkdownLinkCheck:
    enabled: true
    description: 'Checks links in markdown files.'
    required_executable: 'markdown-link-check'
    install_command: 'npm install -g markdown-link-check'
    include: '**/*.md'
